//@RailVision.WebAPI_HostAddress = https://localhost:5001
@RailVision.WebAPI_HostAddress = https://localhost:7060
// @RailVision.WebAPI_HostAddress = http://localhost:32775

### Railways ENDPOINTS

### Get all railways data from overpass API
GET {{RailVision.WebAPI_HostAddress}}/api/railways/data
Accept: application/json

### Get all railways data from database
GET {{RailVision.WebAPI_HostAddress}}/api/railways
Accept: application/json

### Get railway by id from database
GET {{RailVision.WebAPI_HostAddress}}/api/railways/155e9015-aade-4fba-a066-003ae149214c
Accept: application/json

### Get railway by osmId from database
GET {{RailVision.WebAPI_HostAddress}}/api/railways/502033912
Accept: application/json

###

### Stations ENDPOINTS

### Get all stations data from overpass API
GET {{RailVision.WebAPI_HostAddress}}/api/stations/data
Accept: application/json

### Get all stations data from database
GET {{RailVision.WebAPI_HostAddress}}/api/stations
Accept: application/json

### Get station by id from database
GET {{RailVision.WebAPI_HostAddress}}/api/stations/c89fec21-5e7e-453b-bf66-07c8c3645142
Accept: application/json

### Get station by osmId from database
GET {{RailVision.WebAPI_HostAddress}}/api/stations/10771629895
Accept: application/json

### 

### Population Center ENDPOINTS

### Get all population centers data from overpass API
GET {{RailVision.WebAPI_HostAddress}}/api/populationcenters/data
Accept: application/json

### Get all population centers data from database
GET {{RailVision.WebAPI_HostAddress}}/api/populationcenters
Accept: application/json

### Get all population centers data from database with search query
GET {{RailVision.WebAPI_HostAddress}}/api/populationcenters?searchQuery=Bak
Accept: application/json

### Get all population centers data from database with search query and min & max populations
GET {{RailVision.WebAPI_HostAddress}}/api/populationcenters?searchQuery=Ba&minPopulation=50000&maxPopulation=1000000
Accept: application/json

### Get all population centers data from database with min & max populations
GET {{RailVision.WebAPI_HostAddress}}/api/populationcenters?minPopulation=1000&maxPopulation=1000000
Accept: application/json

### Get all population centers data from database with min population
GET {{RailVision.WebAPI_HostAddress}}/api/populationcenters?minPopulation=1000
Accept: application/json

### Get all population centers data from database with max population
GET {{RailVision.WebAPI_HostAddress}}/api/populationcenters?maxPopulation=1000000
Accept: application/json

### Get population center by id from database
GET {{RailVision.WebAPI_HostAddress}}/api/populationcenters/c89fec21-5e7e-453b-bf66-07c8c3645142
Accept: application/json

### Get population center by osmId from database
GET {{RailVision.WebAPI_HostAddress}}/api/populationCenters/10771629895
Accept: application/json

###

### Terrains ENDPOINTS

### Get all terrains data from overpass API
GET {{RailVision.WebAPI_HostAddress}}/api/terrains/data?type=
Accept: application/json

### Get all narutal terrains data from overpass API
GET {{RailVision.WebAPI_HostAddress}}/api/terrains/data?type=natural
Accept: application/json

### Get all man-made terrains data from overpass API
GET {{RailVision.WebAPI_HostAddress}}/api/terrains/data?type=man-made
Accept: application/json

### Get all terrains from database
GET {{RailVision.WebAPI_HostAddress}}/api/terrains
Accept: application/json

### Get terrain by id from database
GET {{RailVision.WebAPI_HostAddress}}/api/terrains/65f7781c-014d-4f68-9eb6-0051605de0be
Accept: application/json
 
### Get terrain by osmId from database
GET {{RailVision.WebAPI_HostAddress}}/api/terrains/302913966
Accept: application/json

###

### Routes ENDPOINTS

### Get optimal route from ids
GET {{RailVision.WebAPI_HostAddress}}/api/routes?FromId=1117022698&ToId=3129805281
Accept: application/json


### Get optimal route from Coordinates
GET {{RailVision.WebAPI_HostAddress}}/api/routes?FromLat=40.4093&FromLon=49.8671&ToLat=39.9400&ToLon=48.9300
Accept: application/json

###

### Redis Cache Management ENDPOINTS

### Get all keys and values from Redis Cache
GET {{RailVision.WebAPI_HostAddress}}/api/cache/redis
Accept: application/json

### Get all keys from Redis Cache
GET {{RailVision.WebAPI_HostAddress}}/api/cache/redis/keys
Accept: application/json

### Get value by key from Redis Cache
GET {{RailVision.WebAPI_HostAddress}}/api/cache/redis/GetAllRailways
Accept: application/json

### Clear all keys and values from Redis Cache
DELETE {{RailVision.WebAPI_HostAddress}}/api/cache/redis

### Clear value by key from Redis Cache
DELETE {{RailVision.WebAPI_HostAddress}}/api/cache/redis/GetAllStations

### InMemory Cache Management ENDPOINTS

### Get all keys and values from InMemory Cache
GET {{RailVision.WebAPI_HostAddress}}/api/cache/inmemory
Accept: application/json

### Get all keys from InMemory Cache
GET {{RailVision.WebAPI_HostAddress}}/api/cache/inmemory/keys
Accept: application/json

### Get value by key from InMemory Cache
GET {{RailVision.WebAPI_HostAddress}}/api/cache/inmemory/GetAllStations
Accept: application/json

### Clear all keys and values from InMemory Cache
DELETE {{RailVision.WebAPI_HostAddress}}/api/cache/inmemory

### Clear value by key from InMemory Cache
DELETE {{RailVision.WebAPI_HostAddress}}/api/cache/inmemory/GetAllStations
